<a href="https://colab.research.google.com/github/kanyaweeud/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Structure (โครงสร้างข้อมูล)**
การเก็บข้อมูลหลาย ๆ ตัวไว้ด้วยกันอย่างเป็นระเบียบ

## **list( )**
1. เก็บอะไรก็ได้
2. ลำดับในการเก็บ มีความสำคัญ

In [ ]:
list_a = [1,2,3,4,5,6]    #[ ] square brackets

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b = ['ab' , 2 , 3.14 , list_a]

In [ ]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

**[3] = สมาชิกตัวที่ 3 โดยนับจาก 0**

In [ ]:
list_a[3]

4

In [ ]:
list_b[3]

[1, 2, 3, 4, 5, 6]

**ชี้สมาชิกใน list ด้วยเลขลำดับของ list = Indexing**

In [ ]:
list_b[3][4]

5

**index - 1 = ตัวสุดท้ายของ list**
(บางทีทำงานไป ขนาดของ list อาจจะเลื่อน)

In [ ]:
list_a[-1]

6

In [ ]:
list_a[-4]

3

# **การสร้าง List**

**แบบที่ 1**

In [ ]:
list_x1 = []

**แบบที่ 2**

In [ ]:
list_x2 = list()

**เอามาเทียบกัน**

In [ ]:
print(list_x1)
print(list_x2)

[]
[]


# **เพิ่มสมาชิกเข้าไปใน list ด้วย append( )**

In [ ]:
list_x1.append(2)

In [ ]:
list_x1

[2]

In [ ]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [ ]:
list_x1[-1]

4

In [ ]:
list_x2

[]

In [ ]:
list_x2.append('ha')

In [ ]:
list_x2

['ha']

# **ลบสมาชิกจาก List**

In [ ]:
list_x1.append('ha')

In [ ]:
list_x1

[2, 4, 'ha', 'ha']

In [ ]:
list_x1.pop()

'ha'

In [ ]:
list_x1

[2, 4, 'ha']

In [ ]:
list_x1.pop()
print(list_x1)

[2, 4]


# **len( ) ตรวจสอบจำนวนสมาชิกของ list**

In [ ]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [ ]:
len(list_a)

6

# **String is a life of characters**

In [ ]:
st_stat = 'Department os Statictics, Faculty of Science'

**ตัวที่ 10 คือตัวอักษรอะไร**

In [ ]:
st_stat[10]

' '

**ตัวที่ 15 คือตัวอักษรอะไร**

In [ ]:
st_stat[15]

't'

**นับจำนวนตัวอักษร**

In [ ]:
len(st_stat)

44

# **List Slicing**



List[จุดเริ่มต้น(จะเป็นวงกลมทึบ) : จุดสุดท้าย(จะเป็นวงกลมโปร่ง)]

List[จุดเริ่มต้น(จะเป็นวงกลมโปร่ง) : จุดสุดท้าย (จะเป็นวงกลมทึบ) :step]

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_a[2]

3

**Colon**

จุดเริ่มต้น: = -3: = ดึงสมาชิก 3  ตัวสุดท้ายของ list

In [ ]:
list_a[-3:]

[4, 5, 6]

In [ ]:
list_a[1:4]

[2, 3, 4]

In [ ]:
list_a[:4]

[1, 2, 3, 4]

In [ ]:
list_a[:]

[1, 2, 3, 4, 5, 6]

**step**

In [ ]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [ ]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [ ]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

# **Range( )** วนลูป

In [ ]:
range(21)

range(0, 21)

เอามาทั้งหมด

In [ ]:
a = list(range(21))

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

# **HW 2**

คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)

1. 12:30:35
2. 13:41:07
3. 09:11:50
4. 21:30:15
5. 03:10:15





In [ ]:
#01:02:03 

a = 1*60*60 + (2*60) + 3
print(f'01:02:03 แปลงเป็นวินาที ได้เท่ากับ {a} วินาที')

01:02:03 แปลงเป็นวินาที ได้เท่ากับ 3723 วินาที


**1. 12:30:35**

In [ ]:
b = (12*60*60) + (30*60) + 35
print(f'12:30:35 แปลงเป็นวินาทีได้เท่ากับ {b} วินาที')

12:30:35 แปลงเป็นวินาทีได้เท่ากับ 45035 วินาที


**2. 13:41:07**

In [ ]:
c = (13*60*60) + (41*60) + 7
print(f'13:41:07 แปลงเป็นวินาทีได้เท่ากับ {c} วินาที')

13:41:07 แปลงเป็นวินาทีได้เท่ากับ 49267 วินาที


**3. 09:11:50**

In [ ]:
d = (9*60*60) + (11*60) + 50
print(f'09:11:50 แปลงเป็นวินาทีได้เท่ากับ {d} วินาที')

09:11:50 แปลงเป็นวินาทีได้เท่ากับ 33110 วินาที


**4. 21:30:15**

In [ ]:
d = (21*60*60) + (30*60) + 15
print(f'21:30:15 แปลงเป็นวินาทีได้เท่ากับ {d} วินาที')

21:30:15 แปลงเป็นวินาทีได้เท่ากับ 77415 วินาที


**5. 03:10:15**

In [ ]:
d = (3*60*60) + (10*60) + 15
print(f'03:10:15 แปลงเป็นวินาทีได้เท่ากับ {d} วินาที')

03:10:15 แปลงเป็นวินาทีได้เท่ากับ 11415 วินาที


# **Dictionary**

**1. การชี้สมาชิกใน Dictionary**



*   คล้าย List ()
*   index เป็นอะไรก็ได้
*   ลำดับไม่มีความสำคัญ





{ } Curly brackets

In [2]:
dict_a = {1: 'Happy' , 'N' : 'New' , '2022' : 'Year'} 

In [3]:
dict_a[1]

'Happy'

In [4]:
dict_a['N']

'New'

In [5]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

**2. การเพิ่มสมาชิกใน Dict**

In [7]:
dict_a[7] = 3.14

In [8]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

หากเขียนทับซ้ำ จะแสดงตัวเล่าสุด

In [9]:
dict_a['N'] = 'NNNEEEEWWW'

In [10]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNEEEEWWW'}

# **Numpy Arry**



*   เก็บได้แค่ตัวเลข
*   อ้างอิงโดยใช้ พิกัด (2 มิติ ก็มองเป็น Matrix)




# 1D arry

In [12]:
import numpy

สามารถแปลงจาก list เป็น array ได้เลย

In [17]:
list_A = [1,2,3,4,5]

In [18]:
arr_a = numpy.array([1,2,3,4,5])

In [19]:
arr_a

array([1, 2, 3, 4, 5])

In [21]:
list_A

[1, 2, 3, 4, 5]

In [22]:
arr_a[0]

1

In [23]:
list_A[0]

1

คุณสมบัติของ Matrix (Scalar Muliplication)

In [24]:
5 * arr_a

array([ 5, 10, 15, 20, 25])

In [25]:
5*list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [26]:
arr_b = numpy.array([10,20,30,40,50])

In [27]:
print(arr_a)

[1 2 3 4 5]


**matrix + matrix**

In [28]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

In [34]:
arr_a.shape

(5,)

# 2D arry

In [29]:
import numpy as np

In [32]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [33]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

**shape = แถว,หลัก**

In [35]:
arr2_z.shape

(2, 3)

**np.zeros()**

In [37]:
arr2_3_5_0 = np.zeros((3,5))

In [42]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

**กำหนดค่า**

In [43]:
arr2_3_5_0[1,2] = 9

In [44]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
arr2_3_5_0[1,2]

9.0

**เปลี่ยนค่าใน list()**

In [46]:
print(list_A)
list_A[-1] = 'christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'christmas']


**np.ones()**

In [47]:
arr2_4_5_1 = np.ones((4,5))

In [48]:
arr2_4_5_1 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
arr2_4_5_200 = 200*np.ones((4,5))

In [50]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

# Matrix operations

**การบวก ลบ matrix $M** ลอกอาจารย์ต่อ

*   $aM$ scalar คูณ Matrix (scalar คูณกระจายเข้าไปทุกตัวของ Matrix)
*   $M\times N$ Matrix คูณ Matrix (แถวคูณหลัก)




  $aM$

In [53]:
5 * arr_a #Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

 $M\times N$  (dot product)
 - (m,n) $\times$ (n,o) = (m,o) (Shape)


In [56]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [57]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [58]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [59]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

**axc , bxc**

In [60]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [61]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

**cxa , cxb**

In [62]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [63]:
np.dot(mat_c,mat_b)

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

In [65]:
mat_X = np.dot(mat_c,mat_b)
print(mat_X)

[[  8  16 -11]
 [ 16  32 -22]
 [ 25  50 -28]]


In [64]:
mat_a * mat_b #เป็นการคูณตำแหน่งเดียวกัน ไม่ตรงตามหลักเมทริกซ์

array([[  2,   6,  25],
       [  8,  24, -49]])

# Matrix Slicing

In [66]:
mat_X[:2,:2] #ตัดเฉพาะส่วนที่ต้องการ

array([[ 8, 16],
       [16, 32]])

# **HW 3**

1.   สร้าง array ที่เป็นรูปต้น christmas
2.   Slice เลข 1 ออกมาจาก array HW3 ด้วยการ Slice แค่ครั้งเดียว


In [67]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [68]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# **Pandas Dataframe (แยกออกไปเป็นโน๊ตบุ๊คเฉพาะ)**