<a href="https://colab.research.google.com/github/kanyaweeud/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Structure (โครงสร้างข้อมูล)**
การเก็บข้อมูลหลาย ๆ ตัวไว้ด้วยกันอย่างเป็นระเบียบ

## **list( )**
1. เก็บอะไรก็ได้
2. ลำดับในการเก็บ มีความสำคัญ

In [5]:
list_a = [1,2,3,4,5,6]    #[ ] square brackets

In [6]:
list_a

[1, 2, 3, 4, 5, 6]

In [7]:
list_b = ['ab' , 2 , 3.14 , list_a]

In [8]:
list_b

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

**[3] = สมาชิกตัวที่ 3 โดยนับจาก 0**

In [9]:
list_a[3]

4

In [10]:
list_b[3]

[1, 2, 3, 4, 5, 6]

**ชี้สมาชิกใน list ด้วยเลขลำดับของ list = Indexing**

In [11]:
list_b[3][4]

5

**index - 1 = ตัวสุดท้ายของ list**
(บางทีทำงานไป ขนาดของ list อาจจะเลื่อน)

In [12]:
list_a[-1]

6

In [13]:
list_a[-4]

3

# **การสร้าง List**

**แบบที่ 1**

In [14]:
list_x1 = []

**แบบที่ 2**

In [15]:
list_x2 = list()

**เอามาเทียบกัน**

In [16]:
print(list_x1)
print(list_x2)

[]
[]


# **เพิ่มสมาชิกเข้าไปใน list ด้วย append( )**

In [17]:
list_x1.append(2)

In [18]:
list_x1

[2]

In [19]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [20]:
list_x1[-1]

4

In [21]:
list_x2

[]

In [22]:
list_x2.append('ha')

In [23]:
list_x2

['ha']

# **ลบสมาชิกจาก List**

In [24]:
list_x1.append('ha')

In [25]:
list_x1

[2, 4, 'ha']

In [26]:
list_x1.pop()

'ha'

In [27]:
list_x1

[2, 4]

In [28]:
list_x1.pop()
print(list_x1)

[2]


# **len( ) ตรวจสอบจำนวนสมาชิกของ list**

In [29]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [30]:
len(list_a)

6

# **String is a life of characters**

In [31]:
st_stat = 'Department os Statictics, Faculty of Science'

**ตัวที่ 10 คือตัวอักษรอะไร**

In [32]:
st_stat[10]

' '

**ตัวที่ 15 คือตัวอักษรอะไร**

In [33]:
st_stat[15]

't'

**นับจำนวนตัวอักษร**

In [34]:
len(st_stat)

44

# **List Slicing**



List[จุดเริ่มต้น(จะเป็นวงกลมทึบ) : จุดสุดท้าย(จะเป็นวงกลมโปร่ง)]

List[จุดเริ่มต้น(จะเป็นวงกลมโปร่ง) : จุดสุดท้าย (จะเป็นวงกลมทึบ) :step]

In [35]:
list_a

[1, 2, 3, 4, 5, 6]

In [36]:
list_a[2]

3

**Colon**

จุดเริ่มต้น: = -3: = ดึงสมาชิก 3  ตัวสุดท้ายของ list

In [37]:
list_a[-3:]

[4, 5, 6]

In [38]:
list_a[1:4]

[2, 3, 4]

In [39]:
list_a[:4]

[1, 2, 3, 4]

In [40]:
list_a[:]

[1, 2, 3, 4, 5, 6]

**step**

In [41]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [42]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [43]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [44]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

# **Range( )** วนลูป

In [45]:
range(21)

range(0, 21)

เอามาทั้งหมด

In [46]:
a = list(range(21))

In [47]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [48]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

# **HW 2**

คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)

1. 12:30:35
2. 13:41:07
3. 09:11:50
4. 21:30:15
5. 03:10:15





In [49]:
#01:02:03 

a = 1*60*60 + (2*60) + 3
print(f'01:02:03 แปลงเป็นวินาที ได้เท่ากับ {a} วินาที')

01:02:03 แปลงเป็นวินาที ได้เท่ากับ 3723 วินาที


**1. 12:30:35**

In [50]:
b = (12*60*60) + (30*60) + 35
print(f'12:30:35 แปลงเป็นวินาทีได้เท่ากับ {b} วินาที')

12:30:35 แปลงเป็นวินาทีได้เท่ากับ 45035 วินาที


**2. 13:41:07**

In [51]:
c = (13*60*60) + (41*60) + 7
print(f'13:41:07 แปลงเป็นวินาทีได้เท่ากับ {c} วินาที')

13:41:07 แปลงเป็นวินาทีได้เท่ากับ 49267 วินาที


**3. 09:11:50**

In [52]:
d = (9*60*60) + (11*60) + 50
print(f'09:11:50 แปลงเป็นวินาทีได้เท่ากับ {d} วินาที')

09:11:50 แปลงเป็นวินาทีได้เท่ากับ 33110 วินาที


**4. 21:30:15**

In [53]:
d = (21*60*60) + (30*60) + 15
print(f'21:30:15 แปลงเป็นวินาทีได้เท่ากับ {d} วินาที')

21:30:15 แปลงเป็นวินาทีได้เท่ากับ 77415 วินาที


**5. 03:10:15**

In [54]:
d = (3*60*60) + (10*60) + 15
print(f'03:10:15 แปลงเป็นวินาทีได้เท่ากับ {d} วินาที')

03:10:15 แปลงเป็นวินาทีได้เท่ากับ 11415 วินาที


# **Dictionary**

**1. การชี้สมาชิกใน Dictionary**



*   คล้าย List ()
*   index เป็นอะไรก็ได้
*   ลำดับไม่มีความสำคัญ





{ } Curly brackets

In [55]:
dict_a = {1: 'Happy' , 'N' : 'New' , '2022' : 'Year'} 

In [56]:
dict_a[1]

'Happy'

In [57]:
dict_a['N']

'New'

In [58]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

**2. การเพิ่มสมาชิกใน Dict**

In [59]:
dict_a[7] = 3.14

In [60]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

หากเขียนทับซ้ำ จะแสดงตัวเล่าสุด

In [61]:
dict_a['N'] = 'NNNEEEEWWW'

In [62]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNEEEEWWW'}

# **Numpy Arry**



*   เก็บได้แค่ตัวเลข
*   อ้างอิงโดยใช้ พิกัด (2 มิติ ก็มองเป็น Matrix)




# 1D arry

In [63]:
import numpy

สามารถแปลงจาก list เป็น array ได้เลย

In [64]:
list_A = [1,2,3,4,5]

In [65]:
arr_a = numpy.array([1,2,3,4,5])

In [66]:
arr_a

array([1, 2, 3, 4, 5])

In [67]:
list_A

[1, 2, 3, 4, 5]

In [68]:
arr_a[0]

1

In [69]:
list_A[0]

1

คุณสมบัติของ Matrix (Scalar Muliplication)

In [70]:
5 * arr_a

array([ 5, 10, 15, 20, 25])

In [71]:
5*list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [72]:
arr_b = numpy.array([10,20,30,40,50])

In [73]:
print(arr_a)

[1 2 3 4 5]


**matrix + matrix**

In [74]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

In [75]:
arr_a.shape

(5,)

# 2D arry

In [76]:
import numpy as np

In [77]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [78]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

**shape = แถว,หลัก**

In [79]:
arr2_z.shape

(2, 3)

**np.zeros()**

In [80]:
arr2_3_5_0 = np.zeros((3,5))

In [81]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

**กำหนดค่า**

In [82]:
arr2_3_5_0[1,2] = 9

In [83]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
arr2_3_5_0[1,2]

9.0

**เปลี่ยนค่าใน list()**

In [85]:
print(list_A)
list_A[-1] = 'christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'christmas']


**np.ones()**

In [86]:
arr2_4_5_1 = np.ones((4,5))

In [87]:
arr2_4_5_1 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [88]:
arr2_4_5_200 = 200*np.ones((4,5))

In [89]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

# Matrix operations

**การบวก ลบ matrix $M** ลอกอาจารย์ต่อ

*   $aM$ scalar คูณ Matrix (scalar คูณกระจายเข้าไปทุกตัวของ Matrix)
*   $M\times N$ Matrix คูณ Matrix (แถวคูณหลัก)




  $aM$

In [90]:
5 * arr_a #Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

 $M\times N$  (dot product)
 - (m,n) $\times$ (n,o) = (m,o) (Shape)


In [91]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [92]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [93]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [94]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

**axc , bxc**

In [95]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [96]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

**cxa , cxb**

In [97]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [98]:
np.dot(mat_c,mat_b)

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

In [99]:
mat_X = np.dot(mat_c,mat_b)
print(mat_X)

[[  8  16 -11]
 [ 16  32 -22]
 [ 25  50 -28]]


In [100]:
mat_a * mat_b #เป็นการคูณตำแหน่งเดียวกัน ไม่ตรงตามหลักเมทริกซ์

array([[  2,   6,  25],
       [  8,  24, -49]])

# Matrix Slicing

In [101]:
mat_X[:2,:2] #ตัดเฉพาะส่วนที่ต้องการ

array([[ 8, 16],
       [16, 32]])

# **HW 3**

1.   สร้าง array ที่เป็นรูปต้น christmas
2.   Slice เลข 1 ออกมาจาก array HW3 ด้วยการ Slice แค่ครั้งเดียว


In [102]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [103]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**ข้อที่ 1**

In [104]:
T = np.ones((15,9))
T[1::,4] = 77
T[3:6,3:6] = 77
T[4:5,4:6:2] = 0
T[5:7,5:7] = 77
T[5:7,2:7] = 77
T[7:9,1:8] = 77
T[6:7,3:7:2] = 0
T[9:12,0:9] = 77
T[8:9,2:8:2] = 0
T[10:11,1:9:2] = 0 
T[12:15,4] = 689
print(T)

[[  1.   1.   1.   1.   1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.  77.   1.   1.   1.   1.]
 [  1.   1.   1.   1.  77.   1.   1.   1.   1.]
 [  1.   1.   1.  77.  77.  77.   1.   1.   1.]
 [  1.   1.   1.  77.   0.  77.   1.   1.   1.]
 [  1.   1.  77.  77.  77.  77.  77.   1.   1.]
 [  1.   1.  77.   0.  77.   0.  77.   1.   1.]
 [  1.  77.  77.  77.  77.  77.  77.  77.   1.]
 [  1.  77.   0.  77.   0.  77.   0.  77.   1.]
 [ 77.  77.  77.  77.  77.  77.  77.  77.  77.]
 [ 77.   0.  77.   0.  77.   0.  77.   0.  77.]
 [ 77.  77.  77.  77.  77.  77.  77.  77.  77.]
 [  1.   1.   1.   1. 689.   1.   1.   1.   1.]
 [  1.   1.   1.   1. 689.   1.   1.   1.   1.]
 [  1.   1.   1.   1. 689.   1.   1.   1.   1.]]


**ข้อที่ 2**

In [109]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [113]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [114]:
HW3[::4,2::2]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# **Pandas Dataframe (แยกออกไปเป็นโน๊ตบุ๊คเฉพาะ)**